# Pytorch Basics

Importing Library and Checking the version

In [10]:
import torch

print(torch.__version__)

1.10.0+cu111


## Pytoch Tensors


A tensor is basically a multi-dimentional array 
- A scalar is 0-dim tensor
- A 1d array is 1-dim tensor
- A matrix is 2-dim tensor, etc

### Defining tensors

In [13]:
# Defining a zero dim tensor
x = torch.tensor(2)
print(x)

# Defining a 1-dim tensor (Vector)
x = torch.tensor([1,2,3,4,5])
print(x)

# Defining a 2-dim tensor (Matrix)
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)

# Defining a n-dim tensor (here n=3)
x = torch.tensor([[[1,4,5], [1,2,3]], [[9,5,2], [4,5,6]]])
print(x)


tensor(2)
tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 4, 5],
         [1, 2, 3]],

        [[9, 5, 2],
         [4, 5, 6]]])


In [23]:
# Tensors with zeros as their values 
x = torch.zeros((3,4)) # (3,4)->dim
print(x)

# Tensors with ones as their values 
x = torch.ones((3,4)) # (3,4)->dim
print(x)


#### Tensors with random values ####
# Intergers
x = torch.randint(low=0, high=10, size=(3,4)) # (3,4)->dim
print(x)

# Values Between 0 to 1
x = torch.rand(3,4) # (3,4)->dim
print(x)

# values that follow normal distribution
x = torch.randn(3,4) # (3,4)->dim
print(x)
print()


# Type of any tensors is <class 'torch.Tensor'>
print(type(x))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[3, 4, 6, 2],
        [7, 0, 4, 1],
        [3, 4, 8, 7]])
tensor([[0.4204, 0.2119, 0.3786, 0.5223],
        [0.9077, 0.3073, 0.1492, 0.7247],
        [0.8912, 0.1823, 0.2290, 0.9724]])
tensor([[-0.1152,  1.0348,  0.2428,  0.1648],
        [ 0.3382, -0.5847, -1.0456,  0.1386],
        [-0.4011,  0.0090,  0.6090,  1.8746]])

<class 'torch.Tensor'>


## Operations on Tensors

In [24]:
# Multiplication with scalar
x = torch.tensor([1,2,3,4])

x*10

tensor([10, 20, 30, 40])

In [27]:
# Addtion of scalar
x = torch.tensor([[1,2,3,4],[1,2,7,5]])
x+10

tensor([[11, 12, 13, 14],
        [11, 12, 17, 15]])

In [28]:
# Addtion of one tensor to  another 
# NOTE: The size of "tensor A" must match the size of "tensor B"
x = torch.tensor([1,2,3,4])
y = torch.tensor([9,19,19,2])

x+y

tensor([10, 21, 22,  6])